"use strict";

const TOOL_MODULES = Object.freeze([
  require("./init-project.js"),
  require("./doctor.js"),
  require("./read-state.js"),
  require("./read-state-summary.js"),
  require("./compare-iterations.js"),
  require("./transition-phase.js"),
  require("./ingest-file.js"),
  require("./inspect-source.js"),
  require("./save-classification.js"),
  require("./acknowledge-inspect.js"),
  require("./record-intent-answer.js"),
  require("./propose-highlights.js"),
  require("./save-brief.js"),
  require("./confirm-brief.js"),
  require("./save-storyboard.js"),
  require("./confirm-storyboard.js"),
  require("./log-storyboarder-invocation.js"),
  require("./log-composer-invocation.js"),
  require("./save-composition.js"),
  require("./lint-composition.js"),
  require("./render-preview.js"),
  require("./snapshot-keyframes.js"),
  require("./qc-stills.js"),
  require("./confirm-preview.js"),
  require("./render-full.js"),
  require("./confirm-render.js"),
  require("./assemble-video.js"),
  require("./package-output.js"),
  require("./import-deliverable.js"),
  require("./finalize-iteration.js"),
  require("./archive-for-iteration.js"),
]);

module.exports = { TOOL_MODULES };
